all: app

app:
	@echo "Building the ELE784 Lab1 application"
	gcc client.c -o ELE784_app

# It's always a good thing to offer a way to cleanup our development directory
clean:
	-rm -f *.o ELE784_app
